### Site Settings ###
title               : Simrn Gupta
description         : >-
                      Every day is a new learning curve :coffee:
                     
                     
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
               # For Documentation Only


### Author Info ###
author:
  name              : Simrn Gupta
  image             : https://mail.google.com/mail/u/0?ui=2&ik=2720689105&attid=0.1&permmsgid=msg-f:1703020662484802437&th=17a25845008e9b85&view=fimg&disp=thd&attbid=ANGjdJ96fEz4sZo6s9rvPy7iVgGkiTrhPyGvsbaYehmW5ZpjanOuNpBaFtH02y0L9xvrvT_FLXvSCjX4J_wS5oOLVtXThzr5RxS4ovLqnzs7VOXwq5xAGYxUYoAKNyk&ats=2524608000000&sz=w1920-h913
#  behance           : your_username
# dribbble          : your_username
  email             : simrangupta877@gmail.com
#  facebook          : your_username
  github            : SimrnGupta
#  gitlab            : SimrnGupta
# instagram         : your_username
# kaggle            : your_username
  linkedin          : simrn-gupta-48146b1a2
  medium            : simrngupta
# soundcloud        : your_username
  spotify           : dt539zc1ks0v3gg5jhuzlrcjh?si=0e2ef02dab5e4c3e
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : GuptaSimrn
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  

### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
